# Generated by Django 5.2.3 on 2025-10-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '论坛分类', 'verbose_name_plural': '论坛分类'},
        ),
    ]
