# Generated by Django 5.2.3 on 2025-10-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_post_options_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
    ]
