# Generated by Django 5.2.3 on 2025-10-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_like_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
